apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerreactjs-yarn
  labels:
    app: dockerreactjs-yarn
spec:
  selector:
    matchLabels:
      app: dockerreactjs-yarn
  template:
    metadata:
      labels:
        app: dockerreactjs-yarn
    spec:
      containers:
      - name: dockerreactjs-yarn-container
        image: ghcr.io/pwdelbloomboard/ps-container
        ports:
        # where the app can be reached inside the container
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi

