apiVersion: v1
kind: Service
metadata:
  name: dockerreactjs-yarn-service
  labels:
    app: dockerreactjs-yarn-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: devops-toolkit
