apiVersion: v1
kind: Service
metadata:
  name: dockerreactjs-yarn-service
  labels:
    app: dockerreactjs-yarn-app
spec:
  type: ClusterIP
  ports:
  # port accessible inside the cluster
  - port: 80
    # port to forward to inside pod
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: dockerreactjs-yarn-app
